import type { Metadata } from 'next'
import '@/app/globals.css'
import { primary, secondary } from '@/app/fonts'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import { Header } from '@/app/components/Header'
import { Footer } from '@/app/components/Footer'
import { ReactQueryProvider } from '../react-query-provider'
import { retrieveCart } from './actions'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()
  await retrieveCart()

  return (
    <html lang={locale}>
      <body
        className={`${primary.variable} ${secondary.variable} flex flex-col overflow-x-hidden antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <ReactQueryProvider>
            <Header />
            <main className="flex flex-1 flex-col overflow-x-hidden">
              {children}
            </main>
            <Footer />
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
