import type { Metadata } from 'next'
import '@/app/globals.css'
import { primary, secondary } from '@/app/fonts'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import Aside from './components/aside'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AnonymousLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body
        className={`${primary.variable} ${secondary.variable} flex flex-col overflow-x-hidden antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <main className="flex min-h-[100vh] w-full flex-col bg-white p-0 sm:flex-row sm:p-10">
            <Aside />
            <section className="flex w-full flex-col gap-5 bg-white p-6 py-10 sm:w-1/3 sm:justify-center sm:gap-14 sm:p-20">
              {children}
            </section>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
