import type { Metadata } from 'next'
import '@/app/globals.css'
import { primary, secondary } from '@/app/fonts'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import { Logo } from '@/app/components/Logo'
import Link from 'next/link'
import {
  ArrowLeft02Icon,
  LanguageSkillIcon,
  QuoteDownIcon,
} from 'hugeicons-react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AnonymousLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body
        className={`${primary.variable} ${secondary.variable} flex flex-col overflow-x-hidden antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <main className="flex min-h-[100vh] w-full flex-col bg-white p-0 sm:flex-row sm:p-10">
            <aside className="flex min-h-[75vh] w-full flex-col justify-between bg-background-base p-6 sm:w-2/3 sm:rounded-lg sm:p-12">
              <div className="pr-6">
                <header className="mb-2 flex flex-col-reverse sm:mb-10 sm:flex-row sm:items-center sm:justify-between">
                  <div className="block sm:hidden">
                    <Logo theme="colored" variant="full" width={150} />
                  </div>
                  <div className="hidden sm:block">
                    <Logo theme="colored" variant="full" width={170} />
                  </div>
                  <div className="flex gap-8">
                    <Link href="" className="inline-flex gap-1">
                      <ArrowLeft02Icon className="size-4 sm:mt-[2px] sm:size-5" />
                      <span className="relative top-[1px] text-xs sm:text-base">
                        Back to shopping
                      </span>
                    </Link>
                    <button
                      type="button"
                      className="inline-flex gap-2 tracking-normal"
                    >
                      <LanguageSkillIcon className="size-4 sm:size-5" />
                      <span className="relative top-[1px] text-xs sm:text-base">
                        Switch to English
                      </span>
                    </button>
                  </div>
                </header>
                <h1 className="text-3xl font-bold sm:mb-6 sm:w-2/3 sm:text-6xl">
                  Find here the right christian book for your spiritual growth.
                </h1>
                <p className="text-base font-light opacity-65 sm:mt-3 sm:w-2/3 sm:text-2xl sm:leading-relaxed sm:opacity-100">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Minima expedita ex delectus.
                </p>
              </div>
              <div className="relative overflow-hidden rounded-lg bg-primary-900 p-5 text-white sm:w-2/3 sm:p-8">
                <p className="font-secondary text-sm font-normal sm:text-2xl sm:font-light sm:leading-normal">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam
                  aliquam ipsam ad corporis distinctio delectus consectetur id
                  commodi sunt numquam nesciunt expedita vel quos molestias,
                  repudiandae dolore quaerat maiores magni!
                </p>
                <h6 className="mt-6 text-sm font-bold sm:text-xl">
                  <Link href="">From The way of life</Link>
                </h6>
                <h5 className="text-sm font-light sm:text-xl">
                  By Zacharias Tanee Fomum
                </h5>
                <QuoteDownIcon
                  size={100}
                  color="#fff"
                  fill="#fff"
                  className="absolute -bottom-[30px] right-[30px] opacity-5"
                />
              </div>
            </aside>
            <section className="flex w-full flex-col gap-5 bg-white p-6 py-10 sm:w-1/3 sm:justify-center sm:gap-14 sm:p-20">
              {children}
            </section>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
