// This file is auto-generated by @hey-api/openapi-ts

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export type Pick_TAuthor_name_or_photo_url_or_about_or_slug_ = {
  slug: string;
  name: string;
  photo_url: string;
  about: string;
};

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export type Pick_TBook_slug_or_title_ = {
  slug: string;
  title: string;
};

export type TApiDataReponse_TBook_ = {
  data: TBook;
};

export type TApiDataReponse_TCategory_Array_ = {
  data: Array<TCategory>;
};

export type TApiDataReponse_TQuote_ = {
  data: TQuote;
};

export type TApiDataReponse_TQuote_Array_ = {
  data: Array<TQuote>;
};

export type TApiPaginatedReponse_TBook_Array_ = {
  offset: number;
  limit: number;
  count: number;
  data: Array<TBook>;
};

export type TAuthor = {
  photo_url: string;
  about: string;
  slug: string;
  name: string;
  id: string;
};

export type TBook = {
  preface: string;
  image_url: string;
  thumbnail: string;
  formats: Array<TFormat>;
  language: TLanguage;
  categories: Array<TCategory>;
  author: TAuthor;
  publisher: string;
  publish_date: number;
  pages_count: number;
  isbn: string;
  ebook_version_url: string;
  dimensions: string;
  audio_version_url: string;
  slug: string;
  title: string;
  id: string;
};

export type TCategory = {
  books?: Array<TBook>;
  rank: number;
  description: string;
  title: string;
  slug: string;
  id: string;
};

export type TCurrency = "eur" | "usd" | "xof";

export type TFormat = {
  prices: Array<TPrice>;
  is_available: boolean;
  label: string;
};

export type TLanguage = {
  code: string;
  id: string;
};

export type TPrice = {
  max_quantity?: number;
  min_quantity?: number;
  currency: TCurrency;
  amount: number;
  id: string;
};

export type TQuote = {
  author: Pick_TAuthor_name_or_photo_url_or_about_or_slug_;
  book: Pick_TBook_slug_or_title_;
  content: string;
  id: string;
};

export type GetQuotesResponse = TApiDataReponse_TQuote_Array_ | void;

export type GetQuotesError = unknown;

export type GetRandomQuoteResponse = TApiDataReponse_TQuote_ | void;

export type GetRandomQuoteError = unknown;

export type GetCategoriesData = {
  query?: {
    includeProducts?: boolean;
  };
};

export type GetCategoriesResponse = TApiDataReponse_TCategory_Array_ | void;

export type GetCategoriesError = unknown;

export type GetBooksData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetBooksResponse = TApiPaginatedReponse_TBook_Array_ | void;

export type GetBooksError = unknown;

export type GetBooksByCategoryData = {
  path: {
    category_id: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetBooksByCategoryResponse =
  TApiPaginatedReponse_TBook_Array_ | void;

export type GetBooksByCategoryError = unknown;

export type GetBookBySlugData = {
  path: {
    slug: string;
  };
};

export type GetBookBySlugResponse = TApiDataReponse_TBook_ | void;

export type GetBookBySlugError = unknown;
