// This file is auto-generated by @hey-api/openapi-ts

export type ApplicationMethod = {
  buy_rules?: Maybe_Array_Maybe_PromotionRule___;
  target_rules?: Maybe_Array_Maybe_PromotionRule___;
  promotion?: Maybe_Promotion_;
  apply_to_quantity?: Maybe_Scalars_at_Int_91_output_93__;
  buy_rules_min_quantity?: Maybe_Scalars_at_Int_91_output_93__;
  max_quantity?: Maybe_Scalars_at_Int_91_output_93__;
  currency_code?: Maybe_Scalars_at_String_91_output_93__;
  value?: Maybe_Scalars_at_Float_91_output_93__;
  allocation?: Maybe_ApplicationMethodAllocationValues_;
  target_type?: Maybe_ApplicationMethodTargetTypeValues_;
  type?: Maybe_ApplicationMethodTypeValues_;
  id: string;
  __typename?: "ApplicationMethod";
};

export type __typename = "ApplicationMethod";

export type ApplicationMethodAllocationValues = "each" | "across";

export type ApplicationMethodTargetTypeValues =
  | "order"
  | "shipping_methods"
  | "items";

export type ApplicationMethodTypeValues = "fixed" | "percentage";

export type Author = {
  quote?: Maybe_Quote_;
  quote_link?: Maybe_LinkQuoteModuleQuoteAuthorModuleAuthor_;
  book?: Maybe_Book_;
  book_link?: Maybe_LinkBookModuleBookAuthorModuleAuthor_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  photoUrl: string;
  about: string;
  name: string;
  handle: string;
  id: string;
  __typename?: "Author";
};

export type __typename2 = "Author";

export type Book = {
  quote?: Maybe_Quote_;
  quote_link?: Maybe_LinkQuoteModuleQuoteBookModuleBook_;
  product?: Maybe_Product_;
  product_link?: Maybe_LinkProductProductBookModuleBook_;
  language?: Maybe_Language_;
  language_link?: Maybe_LinkBookModuleBookLanguageModuleLanguage_;
  author?: Maybe_Author_;
  author_link?: Maybe_LinkBookModuleBookAuthorModuleAuthor_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  raw_publishDate?: Maybe_Scalars_at_JSON_91_output_93__;
  publisher?: Maybe_Scalars_at_String_91_output_93__;
  publishDate?: Maybe_Scalars_at_String_91_output_93__;
  pagesCount?: Maybe_Scalars_at_Int_91_output_93__;
  isbn?: Maybe_Scalars_at_String_91_output_93__;
  ebookVersionEbook?: Maybe_Scalars_at_String_91_output_93__;
  dimensions?: Maybe_Scalars_at_String_91_output_93__;
  audioVersionUrl?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "Book";
};

export type __typename3 = "Book";

export type CalculatedPriceSet = {
  original_price?: Maybe_PriceDetails_;
  calculated_price?: Maybe_PriceDetails_;
  currency_code?: Maybe_Scalars_at_String_91_output_93__;
  raw_original_amount?: Maybe_Scalars_at_JSON_91_output_93__;
  original_amount?: Maybe_Scalars_at_Float_91_output_93__;
  is_original_price_tax_inclusive?: Maybe_Scalars_at_Boolean_91_output_93__;
  is_original_price_price_list?: Maybe_Scalars_at_Boolean_91_output_93__;
  raw_calculated_amount?: Maybe_Scalars_at_JSON_91_output_93__;
  calculated_amount?: Maybe_Scalars_at_Float_91_output_93__;
  is_calculated_price_tax_inclusive?: Maybe_Scalars_at_Boolean_91_output_93__;
  is_calculated_price_price_list?: Maybe_Scalars_at_Boolean_91_output_93__;
  id: string;
  __typename?: "CalculatedPriceSet";
};

export type __typename4 = "CalculatedPriceSet";

export type Campaign = {
  promotions?: Maybe_Array_Maybe_Promotion___;
  budget?: Maybe_CampaignBudget_;
  ends_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  starts_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  campaign_identifier?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  name?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "Campaign";
};

export type __typename5 = "Campaign";

export type CampaignBudget = {
  currency_code?: Maybe_Scalars_at_String_91_output_93__;
  used?: Maybe_Scalars_at_Int_91_output_93__;
  limit?: Maybe_Scalars_at_Int_91_output_93__;
  type?: Maybe_CampaignBudgetTypeValues_;
  id: string;
  __typename?: "CampaignBudget";
};

export type __typename6 = "CampaignBudget";

export type CampaignBudgetTypeValues = "spend" | "usage";

export type ChangeActionType =
  | "CANCEL_RETURN_ITEM"
  | "FULFILL_ITEM"
  | "CANCEL_ITEM_FULFILLMENT"
  | "ITEM_ADD"
  | "ITEM_REMOVE"
  | "ITEM_UPDATE"
  | "RECEIVE_DAMAGED_RETURN_ITEM"
  | "RECEIVE_RETURN_ITEM"
  | "RETURN_ITEM"
  | "SHIPPING_ADD"
  | "SHIPPING_REMOVE"
  | "SHIP_ITEM"
  | "WRITE_OFF_ITEM"
  | "REINSTATE_ITEM";

export type Country = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  region?: Maybe_Region_;
  display_name: string;
  name: string;
  num_code: string;
  iso_3: string;
  iso_2: string;
  __typename?: "Country";
};

export type __typename7 = "Country";

export type Fulfillment = {
  return_link?: Maybe_LinkReturnFulfillment_;
  order?: Maybe_Order_;
  order_link?: Maybe_LinkOrderFulfillment_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  labels: Array<FulfillmentLabel>;
  items: Array<FulfillmentItem>;
  provider: FulfillmentProvider;
  shipping_option?: Maybe_ShippingOption_;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  shipping_option_id?: Maybe_Scalars_at_String_91_output_93__;
  provider_id: string;
  data?: Maybe_Scalars_at_JSON_91_output_93__;
  created_by?: Maybe_Scalars_at_String_91_output_93__;
  marked_shipped_by?: Maybe_Scalars_at_String_91_output_93__;
  canceled_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  delivered_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  shipped_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  packed_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  location_id: string;
  id: string;
  __typename?: "Fulfillment";
};

export type __typename8 = "Fulfillment";

export type FulfillmentItem = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  fulfillment: Fulfillment;
  fulfillment_id: string;
  inventory_item_id?: Maybe_Scalars_at_String_91_output_93__;
  line_item_id?: Maybe_Scalars_at_String_91_output_93__;
  barcode: string;
  sku: string;
  quantity: number;
  title: string;
  id: string;
  __typename?: "FulfillmentItem";
};

export type __typename9 = "FulfillmentItem";

export type FulfillmentLabel = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  fulfillment: Fulfillment;
  fulfillment_id: string;
  label_url: string;
  tracking_url: string;
  tracking_number: string;
  id: string;
  __typename?: "FulfillmentLabel";
};

export type __typename10 = "FulfillmentLabel";

export type FulfillmentProvider = {
  locations?: Maybe_Array_Maybe_StockLocation___;
  locations_link?: Maybe_Array_Maybe_LinkLocationFulfillmentProvider___;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  shipping_options: Array<ShippingOption>;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  name: string;
  id: string;
  __typename?: "FulfillmentProvider";
};

export type __typename11 = "FulfillmentProvider";

export type FulfillmentSet = {
  location?: Maybe_StockLocation_;
  locations_link?: Maybe_LinkLocationFulfillmentSet_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  service_zones: Array<ServiceZone>;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  type: string;
  name: string;
  id: string;
  __typename?: "FulfillmentSet";
};

export type __typename12 = "FulfillmentSet";

export type GeoZone = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  postal_expression?: Maybe_Scalars_at_JSON_91_output_93__;
  city?: Maybe_Scalars_at_String_91_output_93__;
  province_code?: Maybe_Scalars_at_String_91_output_93__;
  country_code: string;
  type: GeoZoneType;
  id: string;
  __typename?: "GeoZone";
};

export type __typename13 = "GeoZone";

export type GeoZoneType = "country" | "province" | "city" | "zip";

export type InventoryItem = {
  variants?: Maybe_Array_Maybe_ProductVariant___;
  variant_link?: Maybe_Array_Maybe_LinkProductVariantInventoryItem___;
  inventory_levels?: Maybe_Array_Maybe_InventoryLevel___;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  thumbnail?: Maybe_Scalars_at_String_91_output_93__;
  title?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  requires_shipping: boolean;
  width?: Maybe_Scalars_at_Int_91_output_93__;
  height?: Maybe_Scalars_at_Int_91_output_93__;
  length?: Maybe_Scalars_at_Int_91_output_93__;
  weight?: Maybe_Scalars_at_Int_91_output_93__;
  material?: Maybe_Scalars_at_String_91_output_93__;
  mid_code?: Maybe_Scalars_at_String_91_output_93__;
  hs_code?: Maybe_Scalars_at_String_91_output_93__;
  origin_country?: Maybe_Scalars_at_String_91_output_93__;
  sku?: Maybe_Scalars_at_String_91_output_93__;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  id: string;
  __typename?: "InventoryItem";
};

export type __typename14 = "InventoryItem";

export type InventoryLevel = {
  stock_locations?: Maybe_Array_Maybe_StockLocation___;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  incoming_quantity: number;
  reserved_quantity: number;
  stocked_quantity: number;
  location_id: string;
  inventory_item: InventoryItem;
  inventory_item_id: string;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  id: string;
  __typename?: "InventoryLevel";
};

export type __typename15 = "InventoryLevel";

export type Language = {
  book?: Maybe_Book_;
  book_link?: Maybe_LinkBookModuleBookLanguageModuleLanguage_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  code: string;
  id: string;
  __typename?: "Language";
};

export type __typename16 = "Language";

export type LinkBookModuleBookAuthorModuleAuthor = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  author_id: string;
  book_id: string;
  __typename?: "LinkBookModuleBookAuthorModuleAuthor";
};

export type __typename17 = "LinkBookModuleBookAuthorModuleAuthor";

export type LinkBookModuleBookLanguageModuleLanguage = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  language_id: string;
  book_id: string;
  __typename?: "LinkBookModuleBookLanguageModuleLanguage";
};

export type __typename18 = "LinkBookModuleBookLanguageModuleLanguage";

export type LinkCartPaymentCollection = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  payment_collection?: Maybe_Payment_;
  payment_collection_id: string;
  cart_id: string;
  __typename?: "LinkCartPaymentCollection";
};

export type __typename19 = "LinkCartPaymentCollection";

export type LinkLocationFulfillmentProvider = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  fulfillment_provider?: Maybe_Fulfillment_;
  location?: Maybe_StockLocation_;
  fulfillment_provider_id: string;
  stock_location_id: string;
  __typename?: "LinkLocationFulfillmentProvider";
};

export type __typename20 = "LinkLocationFulfillmentProvider";

export type LinkLocationFulfillmentSet = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  fulfillment_set?: Maybe_Fulfillment_;
  location?: Maybe_StockLocation_;
  fulfillment_set_id: string;
  stock_location_id: string;
  __typename?: "LinkLocationFulfillmentSet";
};

export type __typename21 = "LinkLocationFulfillmentSet";

export type LinkOrderCart = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  order?: Maybe_Order_;
  cart_id: string;
  order_id: string;
  __typename?: "LinkOrderCart";
};

export type __typename22 = "LinkOrderCart";

export type LinkOrderFulfillment = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  fulfillments?: Maybe_Fulfillment_;
  order?: Maybe_Order_;
  fulfillment_id: string;
  order_id: string;
  __typename?: "LinkOrderFulfillment";
};

export type __typename23 = "LinkOrderFulfillment";

export type LinkOrderPaymentCollection = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  payment_collection?: Maybe_Payment_;
  order?: Maybe_Order_;
  payment_collection_id: string;
  order_id: string;
  __typename?: "LinkOrderPaymentCollection";
};

export type __typename24 = "LinkOrderPaymentCollection";

export type LinkOrderPromotion = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  promotion?: Maybe_Promotion_;
  order?: Maybe_Order_;
  promotion_id: string;
  order_id: string;
  __typename?: "LinkOrderPromotion";
};

export type __typename25 = "LinkOrderPromotion";

export type LinkProductProductBookModuleBook = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  product?: Maybe_Product_;
  book_id: string;
  product_id: string;
  __typename?: "LinkProductProductBookModuleBook";
};

export type __typename26 = "LinkProductProductBookModuleBook";

export type LinkProductSalesChannel = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  sales_channel?: Maybe_SalesChannel_;
  product?: Maybe_Product_;
  sales_channel_id: string;
  product_id: string;
  __typename?: "LinkProductSalesChannel";
};

export type __typename27 = "LinkProductSalesChannel";

export type LinkProductVariantInventoryItem = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  variant?: Maybe_Product_;
  required_quantity: number;
  inventory_item_id: string;
  variant_id: string;
  __typename?: "LinkProductVariantInventoryItem";
};

export type __typename28 = "LinkProductVariantInventoryItem";

export type LinkProductVariantPriceSet = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  variant?: Maybe_Product_;
  price_set_id: string;
  variant_id: string;
  __typename?: "LinkProductVariantPriceSet";
};

export type __typename29 = "LinkProductVariantPriceSet";

export type LinkPublishableApiKeySalesChannel = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  sales_channel?: Maybe_SalesChannel_;
  sales_channel_id: string;
  publishable_key_id: string;
  __typename?: "LinkPublishableApiKeySalesChannel";
};

export type __typename30 = "LinkPublishableApiKeySalesChannel";

export type LinkQuoteModuleQuoteAuthorModuleAuthor = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  author_id: string;
  quote_id: string;
  __typename?: "LinkQuoteModuleQuoteAuthorModuleAuthor";
};

export type __typename31 = "LinkQuoteModuleQuoteAuthorModuleAuthor";

export type LinkQuoteModuleQuoteBookModuleBook = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  book_id: string;
  quote_id: string;
  __typename?: "LinkQuoteModuleQuoteBookModuleBook";
};

export type __typename32 = "LinkQuoteModuleQuoteBookModuleBook";

export type LinkRegionPaymentProvider = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  payment_provider?: Maybe_Payment_;
  region?: Maybe_Region_;
  payment_provider_id: string;
  region_id: string;
  __typename?: "LinkRegionPaymentProvider";
};

export type __typename33 = "LinkRegionPaymentProvider";

export type LinkReturnFulfillment = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  fulfillments?: Maybe_Fulfillment_;
  return?: Maybe_Order_;
  fulfillment_id: string;
  return_id: string;
  __typename?: "LinkReturnFulfillment";
};

export type __typename34 = "LinkReturnFulfillment";

export type LinkSalesChannelStockLocation = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  location?: Maybe_StockLocation_;
  sales_channel?: Maybe_SalesChannel_;
  stock_location_id: string;
  sales_channel_id: string;
  __typename?: "LinkSalesChannelStockLocation";
};

export type __typename35 = "LinkSalesChannelStockLocation";

export type LinkShippingOptionPriceSet = {
  deletedAt?: Maybe_Scalars_at_String_91_output_93__;
  updatedAt: string;
  createdAt: string;
  shipping_option?: Maybe_Fulfillment_;
  price_set_id: string;
  shipping_option_id: string;
  __typename?: "LinkShippingOptionPriceSet";
};

export type __typename36 = "LinkShippingOptionPriceSet";

export type Maybe_ApplicationMethod_ = ApplicationMethod | null;

export type Maybe_ApplicationMethodAllocationValues_ =
  ApplicationMethodAllocationValues | null;

export type Maybe_ApplicationMethodTargetTypeValues_ =
  ApplicationMethodTargetTypeValues | null;

export type Maybe_ApplicationMethodTypeValues_ =
  ApplicationMethodTypeValues | null;

export type Maybe_Array_Maybe_Fulfillment___ = Array<Maybe_Fulfillment_> | null;

export type Maybe_Array_Maybe_FulfillmentProvider___ =
  Array<Maybe_FulfillmentProvider_> | null;

export type Maybe_Array_Maybe_FulfillmentSet___ =
  Array<Maybe_FulfillmentSet_> | null;

export type Maybe_Array_Maybe_InventoryItem___ =
  Array<Maybe_InventoryItem_> | null;

export type Maybe_Array_Maybe_InventoryLevel___ =
  Array<Maybe_InventoryLevel_> | null;

export type Maybe_Array_Maybe_LinkLocationFulfillmentProvider___ =
  Array<Maybe_LinkLocationFulfillmentProvider_> | null;

export type Maybe_Array_Maybe_LinkLocationFulfillmentSet___ =
  Array<Maybe_LinkLocationFulfillmentSet_> | null;

export type Maybe_Array_Maybe_LinkOrderFulfillment___ =
  Array<Maybe_LinkOrderFulfillment_> | null;

export type Maybe_Array_Maybe_LinkProductSalesChannel___ =
  Array<Maybe_LinkProductSalesChannel_> | null;

export type Maybe_Array_Maybe_LinkProductVariantInventoryItem___ =
  Array<Maybe_LinkProductVariantInventoryItem_> | null;

export type Maybe_Array_Maybe_LinkPublishableApiKeySalesChannel___ =
  Array<Maybe_LinkPublishableApiKeySalesChannel_> | null;

export type Maybe_Array_Maybe_LinkRegionPaymentProvider___ =
  Array<Maybe_LinkRegionPaymentProvider_> | null;

export type Maybe_Array_Maybe_LinkReturnFulfillment___ =
  Array<Maybe_LinkReturnFulfillment_> | null;

export type Maybe_Array_Maybe_LinkSalesChannelStockLocation___ =
  Array<Maybe_LinkSalesChannelStockLocation_> | null;

export type Maybe_Array_Maybe_Order___ = Array<Maybe_Order_> | null;

export type Maybe_Array_Maybe_OrderClaimItemImage___ =
  Array<Maybe_OrderClaimItemImage_> | null;

export type Maybe_Array_Maybe_OrderLineItem___ =
  Array<Maybe_OrderLineItem_> | null;

export type Maybe_Array_Maybe_OrderLineItemAdjustment___ =
  Array<Maybe_OrderLineItemAdjustment_> | null;

export type Maybe_Array_Maybe_OrderLineItemTaxLine___ =
  Array<Maybe_OrderLineItemTaxLine_> | null;

export type Maybe_Array_Maybe_OrderShippingMethod___ =
  Array<Maybe_OrderShippingMethod_> | null;

export type Maybe_Array_Maybe_OrderShippingMethodAdjustment___ =
  Array<Maybe_OrderShippingMethodAdjustment_> | null;

export type Maybe_Array_Maybe_OrderShippingMethodTaxLine___ =
  Array<Maybe_OrderShippingMethodTaxLine_> | null;

export type Maybe_Array_Maybe_OrderTransaction___ =
  Array<Maybe_OrderTransaction_> | null;

export type Maybe_Array_Maybe_PaymentCollection___ =
  Array<Maybe_PaymentCollection_> | null;

export type Maybe_Array_Maybe_PaymentProvider___ =
  Array<Maybe_PaymentProvider_> | null;

export type Maybe_Array_Maybe_Price___ = Array<Maybe_Price_> | null;

export type Maybe_Array_Maybe_PriceRule___ = Array<Maybe_PriceRule_> | null;

export type Maybe_Array_Maybe_Product___ = Array<Maybe_Product_> | null;

export type Maybe_Array_Maybe_ProductCategory___ =
  Array<Maybe_ProductCategory_> | null;

export type Maybe_Array_Maybe_ProductVariant___ =
  Array<Maybe_ProductVariant_> | null;

export type Maybe_Array_Maybe_Promotion___ = Array<Maybe_Promotion_> | null;

export type Maybe_Array_Maybe_PromotionRule___ =
  Array<Maybe_PromotionRule_> | null;

export type Maybe_Array_Maybe_Region___ = Array<Maybe_Region_> | null;

export type Maybe_Array_Maybe_SalesChannel___ =
  Array<Maybe_SalesChannel_> | null;

export type Maybe_Array_Maybe_StockLocation___ =
  Array<Maybe_StockLocation_> | null;

export type Maybe_Author_ = Author | null;

export type Maybe_Book_ = Book | null;

export type Maybe_CalculatedPriceSet_ = CalculatedPriceSet | null;

export type Maybe_Campaign_ = Campaign | null;

export type Maybe_CampaignBudget_ = CampaignBudget | null;

export type Maybe_CampaignBudgetTypeValues_ = CampaignBudgetTypeValues | null;

export type Maybe_Country_ = Country | null;

export type Maybe_Fulfillment_ = Fulfillment | null;

export type Maybe_FulfillmentProvider_ = FulfillmentProvider | null;

export type Maybe_FulfillmentSet_ = FulfillmentSet | null;

export type Maybe_InventoryItem_ = InventoryItem | null;

export type Maybe_InventoryLevel_ = InventoryLevel | null;

export type Maybe_Language_ = Language | null;

export type Maybe_LinkBookModuleBookAuthorModuleAuthor_ =
  LinkBookModuleBookAuthorModuleAuthor | null;

export type Maybe_LinkBookModuleBookLanguageModuleLanguage_ =
  LinkBookModuleBookLanguageModuleLanguage | null;

export type Maybe_LinkCartPaymentCollection_ = LinkCartPaymentCollection | null;

export type Maybe_LinkLocationFulfillmentProvider_ =
  LinkLocationFulfillmentProvider | null;

export type Maybe_LinkLocationFulfillmentSet_ =
  LinkLocationFulfillmentSet | null;

export type Maybe_LinkOrderCart_ = LinkOrderCart | null;

export type Maybe_LinkOrderFulfillment_ = LinkOrderFulfillment | null;

export type Maybe_LinkOrderPaymentCollection_ =
  LinkOrderPaymentCollection | null;

export type Maybe_LinkOrderPromotion_ = LinkOrderPromotion | null;

export type Maybe_LinkProductProductBookModuleBook_ =
  LinkProductProductBookModuleBook | null;

export type Maybe_LinkProductSalesChannel_ = LinkProductSalesChannel | null;

export type Maybe_LinkProductVariantInventoryItem_ =
  LinkProductVariantInventoryItem | null;

export type Maybe_LinkProductVariantPriceSet_ =
  LinkProductVariantPriceSet | null;

export type Maybe_LinkPublishableApiKeySalesChannel_ =
  LinkPublishableApiKeySalesChannel | null;

export type Maybe_LinkQuoteModuleQuoteAuthorModuleAuthor_ =
  LinkQuoteModuleQuoteAuthorModuleAuthor | null;

export type Maybe_LinkQuoteModuleQuoteBookModuleBook_ =
  LinkQuoteModuleQuoteBookModuleBook | null;

export type Maybe_LinkRegionPaymentProvider_ = LinkRegionPaymentProvider | null;

export type Maybe_LinkReturnFulfillment_ = LinkReturnFulfillment | null;

export type Maybe_LinkSalesChannelStockLocation_ =
  LinkSalesChannelStockLocation | null;

export type Maybe_LinkShippingOptionPriceSet_ =
  LinkShippingOptionPriceSet | null;

export type Maybe_Order_ = Order | null;

export type Maybe_OrderAddress_ = OrderAddress | null;

export type Maybe_OrderChange_ = OrderChange | null;

export type Maybe_OrderChangeAction_ = OrderChangeAction | null;

export type Maybe_OrderClaim_ = OrderClaim | null;

export type Maybe_OrderClaimItem_ = OrderClaimItem | null;

export type Maybe_OrderClaimItemImage_ = OrderClaimItemImage | null;

export type Maybe_OrderExchange_ = OrderExchange | null;

export type Maybe_OrderExchangeItem_ = OrderExchangeItem | null;

export type Maybe_OrderLineItem_ = OrderLineItem | null;

export type Maybe_OrderLineItemAdjustment_ = OrderLineItemAdjustment | null;

export type Maybe_OrderLineItemTaxLine_ = OrderLineItemTaxLine | null;

export type Maybe_OrderReturnItem_ = OrderReturnItem | null;

export type Maybe_OrderShippingMethod_ = OrderShippingMethod | null;

export type Maybe_OrderShippingMethodAdjustment_ =
  OrderShippingMethodAdjustment | null;

export type Maybe_OrderShippingMethodTaxLine_ =
  OrderShippingMethodTaxLine | null;

export type Maybe_OrderSummary_ = OrderSummary | null;

export type Maybe_OrderTransaction_ = OrderTransaction | null;

export type Maybe_Payment_ = Payment | null;

export type Maybe_PaymentCollection_ = PaymentCollection | null;

export type Maybe_PaymentProvider_ = PaymentProvider | null;

export type Maybe_Price_ = Price | null;

export type Maybe_PriceDetails_ = PriceDetails | null;

export type Maybe_PriceRule_ = PriceRule | null;

export type Maybe_PriceSet_ = PriceSet | null;

export type Maybe_Product_ = Product | null;

export type Maybe_ProductCategory_ = ProductCategory | null;

export type Maybe_ProductCollection_ = ProductCollection | null;

export type Maybe_ProductOption_ = ProductOption | null;

export type Maybe_ProductType_ = ProductType | null;

export type Maybe_ProductVariant_ = ProductVariant | null;

export type Maybe_Promotion_ = Promotion | null;

export type Maybe_PromotionRule_ = PromotionRule | null;

export type Maybe_PromotionRuleOperatorValues_ =
  PromotionRuleOperatorValues | null;

export type Maybe_PromotionTypeValues_ = PromotionTypeValues | null;

export type Maybe_Quote_ = Quote | null;

export type Maybe_Region_ = Region | null;

export type Maybe_Return_ = Return | null;

export type Maybe_SalesChannel_ = SalesChannel | null;

export type Maybe_Scalars_at_Boolean_91_output_93__ = boolean | null;

export type Maybe_Scalars_at_DateTime_91_output_93__ = string | null;

export type Maybe_Scalars_at_Float_91_output_93__ = number | null;

export type Maybe_Scalars_at_ID_91_output_93__ = string | null;

export type Maybe_Scalars_at_Int_91_output_93__ = number | null;

export type Maybe_Scalars_at_JSON_91_output_93__ =
  Record_string_unknown_ | null;

export type Maybe_Scalars_at_String_91_output_93__ = string | null;

export type Maybe_ShippingOption_ = ShippingOption | null;

export type Maybe_StockLocation_ = StockLocation | null;

export type Maybe_StockLocationAddress_ = StockLocationAddress | null;

export type Order = {
  sales_channel?: Maybe_SalesChannel_;
  region?: Maybe_Region_;
  promotion?: Maybe_Array_Maybe_Promotion___;
  promotion_link?: Maybe_LinkOrderPromotion_;
  payment_collections?: Maybe_Array_Maybe_PaymentCollection___;
  payment_collections_link?: Maybe_LinkOrderPaymentCollection_;
  fulfillments?: Maybe_Array_Maybe_Fulfillment___;
  fulfillment_link?: Maybe_Array_Maybe_LinkOrderFulfillment___;
  cart_link?: Maybe_LinkOrderCart_;
  raw_original_shipping_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_shipping_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_shipping_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_shipping_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_shipping_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_shipping_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_gift_card_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_gift_card_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_discount_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_discount_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_item_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_item_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_item_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_item_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_item_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_item_total?: Maybe_Scalars_at_JSON_91_output_93__;
  original_shipping_tax_total: number;
  original_shipping_subtotal: number;
  original_shipping_total: number;
  shipping_tax_total: number;
  shipping_subtotal: number;
  shipping_total: number;
  gift_card_tax_total: number;
  gift_card_total: number;
  discount_tax_total: number;
  discount_total: number;
  tax_total: number;
  subtotal: number;
  total: number;
  original_tax_total: number;
  original_subtotal: number;
  original_total: number;
  item_tax_total: number;
  item_subtotal: number;
  item_total: number;
  original_item_tax_total: number;
  original_item_subtotal: number;
  original_item_total: number;
  updated_at: string;
  created_at: string;
  canceled_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  summary?: Maybe_OrderSummary_;
  transactions?: Maybe_Array_Maybe_OrderTransaction___;
  shipping_methods?: Maybe_Array_Maybe_OrderShippingMethod___;
  items?: Maybe_Array_Maybe_OrderLineItem___;
  billing_address?: Maybe_OrderAddress_;
  shipping_address?: Maybe_OrderAddress_;
  currency_code: string;
  email?: Maybe_Scalars_at_String_91_output_93__;
  sales_channel_id?: Maybe_Scalars_at_String_91_output_93__;
  customer_id?: Maybe_Scalars_at_String_91_output_93__;
  region_id?: Maybe_Scalars_at_String_91_output_93__;
  status: OrderStatus;
  order_change?: Maybe_OrderChange_;
  version: number;
  id: string;
  __typename?: "Order";
};

export type __typename37 = "Order";

export type OrderAddress = {
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  postal_code?: Maybe_Scalars_at_String_91_output_93__;
  province?: Maybe_Scalars_at_String_91_output_93__;
  country_code?: Maybe_Scalars_at_String_91_output_93__;
  city?: Maybe_Scalars_at_String_91_output_93__;
  address_2?: Maybe_Scalars_at_String_91_output_93__;
  address_1?: Maybe_Scalars_at_String_91_output_93__;
  company?: Maybe_Scalars_at_String_91_output_93__;
  phone?: Maybe_Scalars_at_String_91_output_93__;
  last_name?: Maybe_Scalars_at_String_91_output_93__;
  first_name?: Maybe_Scalars_at_String_91_output_93__;
  customer_id?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "OrderAddress";
};

export type __typename38 = "OrderAddress";

export type OrderChange = {
  updated_at: string;
  created_at: string;
  canceled_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  canceled_by?: Maybe_Scalars_at_String_91_output_93__;
  declined_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  declined_reason?: Maybe_Scalars_at_String_91_output_93__;
  declined_by?: Maybe_Scalars_at_String_91_output_93__;
  confirmed_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  confirmed_by?: Maybe_Scalars_at_String_91_output_93__;
  requested_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  requested_by?: Maybe_Scalars_at_String_91_output_93__;
  status: string;
  actions: Array<Maybe_OrderChangeAction_>;
  claim?: Maybe_OrderClaim_;
  exchange?: Maybe_OrderExchange_;
  return_order?: Maybe_Return_;
  order: Order;
  claim_id?: Maybe_Scalars_at_String_91_output_93__;
  exchange_id?: Maybe_Scalars_at_String_91_output_93__;
  return_id?: Maybe_Scalars_at_String_91_output_93__;
  order_id: string;
  change_type?: Maybe_Scalars_at_String_91_output_93__;
  version: number;
  id: string;
  __typename?: "OrderChange";
};

export type __typename39 = "OrderChange";

export type OrderChangeAction = {
  updated_at: string;
  created_at: string;
  internal_note?: Maybe_Scalars_at_String_91_output_93__;
  details?: Maybe_Scalars_at_JSON_91_output_93__;
  action: ChangeActionType;
  reference_id: string;
  reference: string;
  order?: Maybe_Order_;
  exchange_id?: Maybe_Scalars_at_String_91_output_93__;
  claim_id?: Maybe_Scalars_at_String_91_output_93__;
  return_id?: Maybe_Scalars_at_String_91_output_93__;
  order_id?: Maybe_Scalars_at_String_91_output_93__;
  order_change?: Maybe_OrderChange_;
  order_change_id?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "OrderChangeAction";
};

export type __typename40 = "OrderChangeAction";

export type OrderClaim = {
  created_by?: Maybe_Scalars_at_String_91_output_93__;
  refund_amount?: Maybe_Scalars_at_Float_91_output_93__;
  no_notification?: Maybe_Scalars_at_Boolean_91_output_93__;
  return_id?: Maybe_Scalars_at_String_91_output_93__;
  return?: Maybe_Return_;
  additional_items: Array<Maybe_OrderClaimItem_>;
  claim_items: Array<Maybe_OrderClaimItem_>;
  order_id: string;
  __typename?: "OrderClaim";
};

export type __typename41 = "OrderClaim";

export type OrderClaimItem = {
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  images?: Maybe_Array_Maybe_OrderClaimItemImage___;
  quantity: number;
  item_id: string;
  order_id: string;
  claim_id: string;
  id: string;
  __typename?: "OrderClaimItem";
};

export type __typename42 = "OrderClaimItem";

export type OrderClaimItemImage = {
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  url?: Maybe_Scalars_at_String_91_output_93__;
  item: OrderClaimItem;
  claim_item_id: string;
  id: string;
  __typename?: "OrderClaimItemImage";
};

export type __typename43 = "OrderClaimItemImage";

export type OrderExchange = {
  created_by?: Maybe_Scalars_at_String_91_output_93__;
  return_id?: Maybe_Scalars_at_String_91_output_93__;
  return?: Maybe_Return_;
  difference_due?: Maybe_Scalars_at_Float_91_output_93__;
  no_notification?: Maybe_Scalars_at_Boolean_91_output_93__;
  additional_items: Array<Maybe_OrderExchangeItem_>;
  return_items: Array<Maybe_OrderReturnItem_>;
  order_id: string;
  __typename?: "OrderExchange";
};

export type __typename44 = "OrderExchange";

export type OrderExchangeItem = {
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  quantity: number;
  item_id: string;
  order_id: string;
  exchange_id: string;
  id: string;
  __typename?: "OrderExchangeItem";
};

export type __typename45 = "OrderExchangeItem";

export type OrderItem = {
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_written_off_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  written_off_quantity: number;
  raw_return_dismissed_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  return_dismissed_quantity: number;
  raw_return_received_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  return_received_quantity: number;
  raw_return_requested_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  return_requested_quantity: number;
  raw_shipped_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  shipped_quantity: number;
  raw_fulfilled_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  fulfilled_quantity: number;
  raw_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  quantity: number;
  item: OrderLineItem;
  item_id: string;
  id: string;
  __typename?: "OrderItem";
};

export type __typename46 = "OrderItem";

export type OrderLineItem = {
  variant?: Maybe_ProductVariant_;
  product?: Maybe_Product_;
  raw_refundable_total_per_unit?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_refundable_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_discount_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_discount_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_item_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_item_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_item_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_total?: Maybe_Scalars_at_JSON_91_output_93__;
  refundable_total_per_unit?: Maybe_Scalars_at_Float_91_output_93__;
  refundable_total?: Maybe_Scalars_at_Float_91_output_93__;
  discount_tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  discount_total?: Maybe_Scalars_at_Float_91_output_93__;
  tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  total?: Maybe_Scalars_at_Float_91_output_93__;
  item_tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  item_subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  item_total?: Maybe_Scalars_at_Float_91_output_93__;
  original_tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  original_subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  original_total?: Maybe_Scalars_at_Float_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  updated_at: string;
  created_at: string;
  detail: OrderItem;
  adjustments?: Maybe_Array_Maybe_OrderLineItemAdjustment___;
  tax_lines?: Maybe_Array_Maybe_OrderLineItemTaxLine___;
  raw_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  quantity: number;
  raw_unit_price?: Maybe_Scalars_at_JSON_91_output_93__;
  unit_price: number;
  raw_compare_at_unit_price?: Maybe_Scalars_at_JSON_91_output_93__;
  compare_at_unit_price?: Maybe_Scalars_at_Float_91_output_93__;
  is_tax_inclusive: boolean;
  is_discountable: boolean;
  requires_shipping: boolean;
  variant_option_values?: Maybe_Scalars_at_JSON_91_output_93__;
  variant_title?: Maybe_Scalars_at_String_91_output_93__;
  variant_barcode?: Maybe_Scalars_at_String_91_output_93__;
  variant_sku?: Maybe_Scalars_at_String_91_output_93__;
  product_handle?: Maybe_Scalars_at_String_91_output_93__;
  product_collection?: Maybe_Scalars_at_String_91_output_93__;
  product_type_id?: Maybe_Scalars_at_String_91_output_93__;
  product_type?: Maybe_Scalars_at_String_91_output_93__;
  product_subtitle?: Maybe_Scalars_at_String_91_output_93__;
  product_description?: Maybe_Scalars_at_String_91_output_93__;
  product_title?: Maybe_Scalars_at_String_91_output_93__;
  product_id?: Maybe_Scalars_at_String_91_output_93__;
  variant_id?: Maybe_Scalars_at_String_91_output_93__;
  thumbnail?: Maybe_Scalars_at_String_91_output_93__;
  subtitle?: Maybe_Scalars_at_String_91_output_93__;
  title: string;
  id: string;
  __typename?: "OrderLineItem";
};

export type __typename47 = "OrderLineItem";

export type OrderLineItemAdjustment = {
  item_id: string;
  item?: Maybe_OrderLineItem_;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  provider_id?: Maybe_Scalars_at_String_91_output_93__;
  promotion_id?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  order_id: string;
  amount?: Maybe_Scalars_at_Float_91_output_93__;
  code?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "OrderLineItemAdjustment";
};

export type __typename48 = "OrderLineItemAdjustment";

export type OrderLineItemTaxLine = {
  raw_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_total?: Maybe_Scalars_at_JSON_91_output_93__;
  subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  total?: Maybe_Scalars_at_Float_91_output_93__;
  item_id: string;
  item?: Maybe_OrderLineItem_;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  provider_id?: Maybe_Scalars_at_String_91_output_93__;
  rate?: Maybe_Scalars_at_Float_91_output_93__;
  code: string;
  tax_rate_id?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "OrderLineItemTaxLine";
};

export type __typename49 = "OrderLineItemTaxLine";

export type OrderReturnItem = {
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_received_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  received_quantity?: Maybe_Scalars_at_Int_91_output_93__;
  raw_quantity?: Maybe_Scalars_at_JSON_91_output_93__;
  quantity: number;
  reason_id?: Maybe_Scalars_at_String_91_output_93__;
  item_id: string;
  order_id: string;
  return_id: string;
  id: string;
  __typename?: "OrderReturnItem";
};

export type __typename50 = "OrderReturnItem";

export type OrderShippingMethod = {
  raw_discount_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_discount_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_tax_total?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_original_total?: Maybe_Scalars_at_JSON_91_output_93__;
  discount_tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  discount_total?: Maybe_Scalars_at_Float_91_output_93__;
  tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  total?: Maybe_Scalars_at_Float_91_output_93__;
  original_tax_total?: Maybe_Scalars_at_Float_91_output_93__;
  original_subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  original_total?: Maybe_Scalars_at_Float_91_output_93__;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  adjustments?: Maybe_Array_Maybe_OrderShippingMethodAdjustment___;
  tax_lines?: Maybe_Array_Maybe_OrderShippingMethodTaxLine___;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  data?: Maybe_Scalars_at_JSON_91_output_93__;
  shipping_option_id?: Maybe_Scalars_at_String_91_output_93__;
  is_tax_inclusive?: Maybe_Scalars_at_Boolean_91_output_93__;
  raw_amount?: Maybe_Scalars_at_JSON_91_output_93__;
  amount?: Maybe_Scalars_at_Float_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  name: string;
  order_id: string;
  id: string;
  __typename?: "OrderShippingMethod";
};

export type __typename51 = "OrderShippingMethod";

export type OrderShippingMethodAdjustment = {
  shipping_method_id: string;
  shipping_method?: Maybe_OrderShippingMethod_;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  provider_id?: Maybe_Scalars_at_String_91_output_93__;
  promotion_id?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  order_id: string;
  amount?: Maybe_Scalars_at_Float_91_output_93__;
  code?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "OrderShippingMethodAdjustment";
};

export type __typename52 = "OrderShippingMethodAdjustment";

export type OrderShippingMethodTaxLine = {
  raw_subtotal?: Maybe_Scalars_at_JSON_91_output_93__;
  raw_total?: Maybe_Scalars_at_JSON_91_output_93__;
  subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  total?: Maybe_Scalars_at_Float_91_output_93__;
  shipping_method_id: string;
  shipping_method?: Maybe_OrderShippingMethod_;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  provider_id?: Maybe_Scalars_at_String_91_output_93__;
  rate?: Maybe_Scalars_at_Float_91_output_93__;
  code: string;
  tax_rate_id?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "OrderShippingMethodTaxLine";
};

export type __typename53 = "OrderShippingMethodTaxLine";

export type OrderStatus =
  | "pending"
  | "completed"
  | "draft"
  | "archived"
  | "canceled"
  | "requires_action";

export type OrderSummary = {
  raw_pending_difference?: Maybe_Scalars_at_JSON_91_output_93__;
  pending_difference?: Maybe_Scalars_at_Float_91_output_93__;
  refunded_total?: Maybe_Scalars_at_Float_91_output_93__;
  paid_total?: Maybe_Scalars_at_Float_91_output_93__;
  balance?: Maybe_Scalars_at_Float_91_output_93__;
  net_total_tax?: Maybe_Scalars_at_Float_91_output_93__;
  net_subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  net_total?: Maybe_Scalars_at_Float_91_output_93__;
  projected_total?: Maybe_Scalars_at_Float_91_output_93__;
  write_off_total?: Maybe_Scalars_at_Float_91_output_93__;
  return_request_total?: Maybe_Scalars_at_Float_91_output_93__;
  returned_total?: Maybe_Scalars_at_Float_91_output_93__;
  fulfilled_total?: Maybe_Scalars_at_Float_91_output_93__;
  ordered_total?: Maybe_Scalars_at_Float_91_output_93__;
  total_tax?: Maybe_Scalars_at_Float_91_output_93__;
  subtotal?: Maybe_Scalars_at_Float_91_output_93__;
  total?: Maybe_Scalars_at_Float_91_output_93__;
  __typename?: "OrderSummary";
};

export type __typename54 = "OrderSummary";

export type OrderTransaction = {
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  reference_id: string;
  reference: string;
  currency_code: string;
  raw_amount?: Maybe_Scalars_at_JSON_91_output_93__;
  amount: number;
  order: Order;
  order_id: string;
  id: string;
  __typename?: "OrderTransaction";
};

export type __typename55 = "OrderTransaction";

export type Payment = {
  payment_collection_id: string;
  raw_refunded_amount?: Maybe_Scalars_at_Float_91_output_93__;
  refunded_amount?: Maybe_Scalars_at_Float_91_output_93__;
  raw_captured_amount?: Maybe_Scalars_at_Float_91_output_93__;
  captured_amount?: Maybe_Scalars_at_Float_91_output_93__;
  canceled_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  captured_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  data?: Maybe_Scalars_at_JSON_91_output_93__;
  customer_id?: Maybe_Scalars_at_String_91_output_93__;
  order_edit_id?: Maybe_Scalars_at_String_91_output_93__;
  order_id?: Maybe_Scalars_at_String_91_output_93__;
  cart_id?: Maybe_Scalars_at_String_91_output_93__;
  provider_id: string;
  currency_code: string;
  raw_authorized_amount?: Maybe_Scalars_at_Float_91_output_93__;
  authorized_amount?: Maybe_Scalars_at_Float_91_output_93__;
  raw_amount?: Maybe_Scalars_at_Float_91_output_93__;
  amount: number;
  id: string;
  __typename?: "Payment";
};

export type __typename56 = "Payment";

export type PaymentCollection = {
  order?: Maybe_Order_;
  order_link?: Maybe_LinkOrderPaymentCollection_;
  cart_link?: Maybe_LinkCartPaymentCollection_;
  status: PaymentCollectionStatus;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  completed_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  captured_amount?: Maybe_Scalars_at_Float_91_output_93__;
  refunded_amount?: Maybe_Scalars_at_Float_91_output_93__;
  authorized_amount?: Maybe_Scalars_at_Float_91_output_93__;
  amount: number;
  region_id: string;
  currency_code: string;
  id: string;
  __typename?: "PaymentCollection";
};

export type __typename57 = "PaymentCollection";

export type PaymentCollectionStatus =
  | "not_paid"
  | "awaiting"
  | "authorized"
  | "partially_authorized"
  | "canceled";

export type PaymentProvider = {
  regions?: Maybe_Array_Maybe_Region___;
  region_link?: Maybe_Array_Maybe_LinkRegionPaymentProvider___;
  is_enabled: string;
  id: string;
  __typename?: "PaymentProvider";
};

export type __typename58 = "PaymentProvider";

export type Price = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  price_rules?: Maybe_Array_Maybe_PriceRule___;
  rules_count?: Maybe_Scalars_at_Int_91_output_93__;
  max_quantity?: Maybe_Scalars_at_Float_91_output_93__;
  min_quantity?: Maybe_Scalars_at_Float_91_output_93__;
  amount?: Maybe_Scalars_at_Float_91_output_93__;
  currency_code?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "Price";
};

export type __typename59 = "Price";

export type PriceDetails = {
  max_quantity?: Maybe_Scalars_at_Float_91_output_93__;
  min_quantity?: Maybe_Scalars_at_Float_91_output_93__;
  price_list_type?: Maybe_Scalars_at_String_91_output_93__;
  price_list_id?: Maybe_Scalars_at_String_91_output_93__;
  id?: Maybe_Scalars_at_ID_91_output_93__;
  __typename?: "PriceDetails";
};

export type __typename60 = "PriceDetails";

export type PriceRule = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  created_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  price_list_id: string;
  price_id: string;
  priority: number;
  value: string;
  attribute: string;
  price_set?: Maybe_PriceSet_;
  price_set_id: string;
  id: string;
  __typename?: "PriceRule";
};

export type __typename61 = "PriceRule";

export type PriceSet = {
  shipping_option?: Maybe_ShippingOption_;
  shipping_option_link?: Maybe_LinkShippingOptionPriceSet_;
  variant?: Maybe_ProductVariant_;
  variant_link?: Maybe_LinkProductVariantPriceSet_;
  calculated_price?: Maybe_CalculatedPriceSet_;
  prices?: Maybe_Array_Maybe_Price___;
  id: string;
  __typename?: "PriceSet";
};

export type __typename62 = "PriceSet";

export type Product = {
  book?: Maybe_Book_;
  book_link?: Maybe_LinkProductProductBookModuleBook_;
  sales_channels?: Maybe_Array_Maybe_SalesChannel___;
  sales_channels_link?: Maybe_Array_Maybe_LinkProductSalesChannel___;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  external_id?: Maybe_Scalars_at_String_91_output_93__;
  discountable?: Maybe_Scalars_at_Boolean_91_output_93__;
  images: Array<ProductImage>;
  options: Array<ProductOption>;
  variants: Array<ProductVariant>;
  tags: Array<ProductTag>;
  type_id?: Maybe_Scalars_at_String_91_output_93__;
  type?: Maybe_ProductType_;
  categories?: Maybe_Array_Maybe_ProductCategory___;
  collection_id?: Maybe_Scalars_at_String_91_output_93__;
  collection?: Maybe_ProductCollection_;
  material?: Maybe_Scalars_at_String_91_output_93__;
  mid_code?: Maybe_Scalars_at_String_91_output_93__;
  hs_code?: Maybe_Scalars_at_String_91_output_93__;
  origin_country?: Maybe_Scalars_at_String_91_output_93__;
  height?: Maybe_Scalars_at_Float_91_output_93__;
  length?: Maybe_Scalars_at_Float_91_output_93__;
  weight?: Maybe_Scalars_at_Float_91_output_93__;
  width?: Maybe_Scalars_at_Float_91_output_93__;
  thumbnail?: Maybe_Scalars_at_String_91_output_93__;
  status: ProductStatus;
  is_giftcard: boolean;
  description?: Maybe_Scalars_at_String_91_output_93__;
  subtitle?: Maybe_Scalars_at_String_91_output_93__;
  handle: string;
  title: string;
  id: string;
  __typename?: "Product";
};

export type __typename63 = "Product";

export type ProductCategory = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  products: Array<Product>;
  category_children: Array<ProductCategory>;
  parent_category_id?: Maybe_Scalars_at_String_91_output_93__;
  parent_category?: Maybe_ProductCategory_;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  rank: number;
  is_internal: boolean;
  is_active: boolean;
  handle: string;
  description: string;
  name: string;
  id: string;
  __typename?: "ProductCategory";
};

export type __typename64 = "ProductCategory";

export type ProductCollection = {
  products?: Maybe_Array_Maybe_Product___;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  handle: string;
  title: string;
  id: string;
  __typename?: "ProductCollection";
};

export type __typename65 = "ProductCollection";

export type ProductImage = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  url: string;
  id: string;
  __typename?: "ProductImage";
};

export type __typename66 = "ProductImage";

export type ProductOption = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  values: Array<ProductOptionValue>;
  product_id?: Maybe_Scalars_at_String_91_output_93__;
  product?: Maybe_Product_;
  title: string;
  id: string;
  __typename?: "ProductOption";
};

export type __typename67 = "ProductOption";

export type ProductOptionValue = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  option_id?: Maybe_Scalars_at_String_91_output_93__;
  option?: Maybe_ProductOption_;
  value: string;
  id: string;
  __typename?: "ProductOptionValue";
};

export type __typename68 = "ProductOptionValue";

export type ProductStatus = "draft" | "proposed" | "published" | "rejected";

export type ProductTag = {
  products?: Maybe_Array_Maybe_Product___;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  value: string;
  id: string;
  __typename?: "ProductTag";
};

export type __typename69 = "ProductTag";

export type ProductType = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  value: string;
  id: string;
  __typename?: "ProductType";
};

export type __typename70 = "ProductType";

export type ProductVariant = {
  order_items?: Maybe_Array_Maybe_OrderLineItem___;
  price_set?: Maybe_PriceSet_;
  price_set_link?: Maybe_LinkProductVariantPriceSet_;
  inventory?: Maybe_Array_Maybe_InventoryItem___;
  inventory_items?: Maybe_Array_Maybe_LinkProductVariantInventoryItem___;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  variant_rank?: Maybe_Scalars_at_Int_91_output_93__;
  product_id?: Maybe_Scalars_at_String_91_output_93__;
  product?: Maybe_Product_;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  options: Array<ProductOptionValue>;
  width?: Maybe_Scalars_at_Float_91_output_93__;
  height?: Maybe_Scalars_at_Float_91_output_93__;
  length?: Maybe_Scalars_at_Float_91_output_93__;
  weight?: Maybe_Scalars_at_Float_91_output_93__;
  material?: Maybe_Scalars_at_String_91_output_93__;
  mid_code?: Maybe_Scalars_at_String_91_output_93__;
  origin_country?: Maybe_Scalars_at_String_91_output_93__;
  hs_code?: Maybe_Scalars_at_String_91_output_93__;
  requires_shipping: boolean;
  manage_inventory: boolean;
  allow_backorder: boolean;
  upc?: Maybe_Scalars_at_String_91_output_93__;
  ean?: Maybe_Scalars_at_String_91_output_93__;
  barcode?: Maybe_Scalars_at_String_91_output_93__;
  sku?: Maybe_Scalars_at_String_91_output_93__;
  title: string;
  id: string;
  __typename?: "ProductVariant";
};

export type __typename71 = "ProductVariant";

export type Promotion = {
  order_link?: Maybe_LinkOrderPromotion_;
  campaign?: Maybe_Campaign_;
  campaign_id?: Maybe_Scalars_at_String_91_output_93__;
  rules?: Maybe_Array_Maybe_PromotionRule___;
  application_method?: Maybe_ApplicationMethod_;
  is_automatic?: Maybe_Scalars_at_Boolean_91_output_93__;
  type?: Maybe_PromotionTypeValues_;
  code?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "Promotion";
};

export type __typename72 = "Promotion";

export type PromotionRule = {
  values: Array<PromotionRuleValue>;
  operator?: Maybe_PromotionRuleOperatorValues_;
  attribute?: Maybe_Scalars_at_String_91_output_93__;
  description?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "PromotionRule";
};

export type __typename73 = "PromotionRule";

export type PromotionRuleOperatorValues =
  | "gt"
  | "lt"
  | "eq"
  | "ne"
  | "in"
  | "lte"
  | "gte";

export type PromotionRuleValue = {
  value?: Maybe_Scalars_at_String_91_output_93__;
  id: string;
  __typename?: "PromotionRuleValue";
};

export type __typename74 = "PromotionRuleValue";

export type PromotionTypeValues = "standard" | "buyget";

export type Quote = {
  book?: Maybe_Book_;
  book_link?: Maybe_LinkQuoteModuleQuoteBookModuleBook_;
  author?: Maybe_Author_;
  author_link?: Maybe_LinkQuoteModuleQuoteAuthorModuleAuthor_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  details?: Maybe_Scalars_at_String_91_output_93__;
  content: string;
  id: string;
  __typename?: "Quote";
};

export type __typename75 = "Quote";

/**
 * Construct a type with a set of properties K of type T
 */
export type Record_string_unknown_ = {
  [key: string]: unknown;
};

export type Region = {
  payment_providers?: Maybe_Array_Maybe_PaymentProvider___;
  payment_provider_link?: Maybe_Array_Maybe_LinkRegionPaymentProvider___;
  orders?: Maybe_Array_Maybe_Order___;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  countries: Array<Maybe_Country_>;
  automatic_taxes: boolean;
  currency_code: string;
  name: string;
  id: string;
  __typename?: "Region";
};

export type __typename76 = "Region";

export type Return = {
  return_fulfillments?: Maybe_Array_Maybe_Fulfillment___;
  return_fulfillment_link?: Maybe_Array_Maybe_LinkReturnFulfillment___;
  items: Array<Maybe_OrderReturnItem_>;
  order_id: string;
  refund_amount?: Maybe_Scalars_at_Float_91_output_93__;
  status: ReturnStatus;
  id: string;
  __typename?: "Return";
};

export type __typename77 = "Return";

export type ReturnStatus =
  | "requested"
  | "received"
  | "partially_received"
  | "canceled";

export type SalesChannel = {
  stock_locations?: Maybe_Array_Maybe_StockLocation___;
  locations_link?: Maybe_Array_Maybe_LinkSalesChannelStockLocation___;
  orders?: Maybe_Array_Maybe_Order___;
  api_keys_link?: Maybe_Array_Maybe_LinkPublishableApiKeySalesChannel___;
  products_link?: Maybe_Array_Maybe_LinkProductSalesChannel___;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  created_at: string;
  is_disabled: boolean;
  description?: Maybe_Scalars_at_String_91_output_93__;
  name: string;
  id: string;
  __typename?: "SalesChannel";
};

export type __typename78 = "SalesChannel";

export type ServiceZone = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  shipping_options: Array<ShippingOption>;
  geo_zones: Array<GeoZone>;
  fulfillment_set_id: string;
  fulfillment_set: FulfillmentSet;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  name: string;
  id: string;
  __typename?: "ServiceZone";
};

export type __typename79 = "ServiceZone";

export type ShippingOption = {
  price_set_link?: Maybe_LinkShippingOptionPriceSet_;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  fulfillments: Array<Fulfillment>;
  rules: Array<ShippingOptionRule>;
  type: ShippingOptionType;
  fulfillment_provider: FulfillmentProvider;
  shipping_profile: ShippingProfile;
  service_zone: ServiceZone;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  data?: Maybe_Scalars_at_JSON_91_output_93__;
  shipping_option_type_id?: Maybe_Scalars_at_String_91_output_93__;
  provider_id: string;
  shipping_profile_id: string;
  service_zone_id: string;
  price_type: ShippingOptionPriceType;
  name: string;
  id: string;
  __typename?: "ShippingOption";
};

export type __typename80 = "ShippingOption";

export type ShippingOptionPriceType = "calculated" | "flat";

export type ShippingOptionRule = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  shipping_option: ShippingOption;
  shipping_option_id: string;
  value?: Maybe_Scalars_at_JSON_91_output_93__;
  operator: string;
  attribute: string;
  id: string;
  __typename?: "ShippingOptionRule";
};

export type __typename81 = "ShippingOptionRule";

export type ShippingOptionType = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  shipping_option: ShippingOption;
  shipping_option_id: string;
  code: string;
  description: string;
  label: string;
  id: string;
  __typename?: "ShippingOptionType";
};

export type __typename82 = "ShippingOptionType";

export type ShippingProfile = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  shipping_options: Array<ShippingOption>;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  type: string;
  name: string;
  id: string;
  __typename?: "ShippingProfile";
};

export type __typename83 = "ShippingProfile";

export type StockLocation = {
  sales_channels?: Maybe_Array_Maybe_SalesChannel___;
  sales_channels_link?: Maybe_Array_Maybe_LinkSalesChannelStockLocation___;
  fulfillment_sets?: Maybe_Array_Maybe_FulfillmentSet___;
  fulfillment_set_link?: Maybe_Array_Maybe_LinkLocationFulfillmentSet___;
  fulfillment_providers?: Maybe_Array_Maybe_FulfillmentProvider___;
  fulfillment_provider_link?: Maybe_Array_Maybe_LinkLocationFulfillmentProvider___;
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  address?: Maybe_StockLocationAddress_;
  address_id: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  name: string;
  id: string;
  __typename?: "StockLocation";
};

export type __typename84 = "StockLocation";

export type StockLocationAddress = {
  deleted_at?: Maybe_Scalars_at_DateTime_91_output_93__;
  updated_at: string;
  created_at: string;
  metadata?: Maybe_Scalars_at_JSON_91_output_93__;
  province?: Maybe_Scalars_at_String_91_output_93__;
  postal_code?: Maybe_Scalars_at_String_91_output_93__;
  phone?: Maybe_Scalars_at_String_91_output_93__;
  city?: Maybe_Scalars_at_String_91_output_93__;
  country_code: string;
  company?: Maybe_Scalars_at_String_91_output_93__;
  address_2?: Maybe_Scalars_at_String_91_output_93__;
  address_1: string;
  id?: Maybe_Scalars_at_ID_91_output_93__;
  __typename?: "StockLocationAddress";
};

export type __typename85 = "StockLocationAddress";

export type TApiDataReponse_Product_ = {
  data: Product;
};

export type TApiDataReponse_ProductCategory_ = {
  data: ProductCategory;
};

export type TApiDataReponse_ProductCategory_Array_ = {
  data: Array<ProductCategory>;
};

export type TApiDataReponse_Quote_Array_ = {
  data: Array<Quote>;
};

export type TApiPaginatedReponse_Product_Array_ = {
  offset: number;
  limit: number;
  count: number;
  data: Array<Product>;
};

export type GetQuotesResponse = TApiDataReponse_Quote_Array_ | void;

export type GetQuotesError = unknown;

export type GetRandomQuoteResponse = TApiDataReponse_Quote_Array_ | void;

export type GetRandomQuoteError = unknown;

export type GetCategoriesData = {
  query?: {
    includeProducts?: boolean;
  };
};

export type GetCategoriesResponse =
  TApiDataReponse_ProductCategory_Array_ | void;

export type GetCategoriesError = unknown;

export type GetCategoryBySlugData = {
  path: {
    slug: string;
  };
};

export type GetCategoryBySlugResponse = TApiDataReponse_ProductCategory_ | void;

export type GetCategoryBySlugError = unknown;

export type GetBooksData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetBooksResponse = TApiPaginatedReponse_Product_Array_ | void;

export type GetBooksError = unknown;

export type GetBooksByCategoryData = {
  path: {
    category_id: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type GetBooksByCategoryResponse =
  TApiPaginatedReponse_Product_Array_ | void;

export type GetBooksByCategoryError = unknown;

export type GetBookBySlugData = {
  path: {
    slug: string;
  };
};

export type GetBookBySlugResponse = TApiDataReponse_Product_ | void;

export type GetBookBySlugError = unknown;

export type GetRecommendationResponse = string | void;

export type GetRecommendationError = unknown;
