// This file is auto-generated by @hey-api/openapi-ts

export type GetData = {
  query: {
    limit: number;
    offset: number;
  };
};

export type GetResponse = void;

export type GetError = unknown;
